spring:
  config:
    activate:
      on-profile:
      - dev
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
  application:
    environment: dev
    version: 1.0
    name: ${APPLICATION_NAME:weatherapi}
  output:
    ansi:
      enabled: ALWAYS
server:
  port: ${SERVER_PORT:9095}
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /weather
logging:
  level:
    com:
      roberto: ${LOG_LEVEL:INFO}
url:
  weather: ${URL_WEATHER_API:http://api.weatherapi.com/v1/}
  key: ${KEY_API:ea6ac94922bf41b8ad4211249232303}
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
